"""empty message

Revision ID: 019e8c827786
Revises: 9423eaedfdf8
Create Date: 2020-11-02 16:42:03.038162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019e8c827786'
down_revision = '9423eaedfdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint('user', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
